name: token_bucket_algorithm
description: "Implementation of the token bucket algorithm."
version: 0.1.1
repository: https://github.com/splashbyte/dart_token_bucket_algorithm
issue_tracker: https://github.com/splashbyte/dart_token_bucket_algorithm/issues

topics:
  - rate-limit
  - token-bucket
  - algorithm
  - security

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  clock: ^1.1.1

dev_dependencies:
  test: '>=1.15.0 <2.0.0'
  lints: ^4.0.0
  fake_async: ^1.3.1
  mocktail: ^1.0.4
